"""
Figure 3C — Residue binding (binary): embedding space ranking
=============================================================
Reproduces Figure 3C

Panel layout (generated by shared_figures.plot_model_ranking):
  Left:  KNN feature alignment score vs k (cosine, mean-centred, k in [5,10,20,30,50,100])
  Right: Bar chart of F1 scores as reported by Heinzinger et al. (2024)

PLMs compared: Ankh, ProtT5, ProstT5, ESM2
Output saved to: examples/paper/figures/figure3/figure3c_residue_binding.pdf
"""

import os
import sys

import numpy as np
import pandas as pd
import plotly.colors as pc

from emmaemb.core import Emma
from emmaemb.functions import get_knn_alignment_scores

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))
from shared_figures import plot_model_ranking

# ── Path placeholders — fill in before running ─────────────────────────────────
EMBEDDINGS_DIR = "examples/paper/data/binding/embeddings/"          # subdirs: ModelName/per_residue/
FEATURES_CSV   = "examples/paper/data/binding/processed/binding_train_features.csv"
BACKUP_DIR     = "examples/paper/data/binding/ranks/centered/"         # cached rank arrays (mean-centred)
OUTPUT_DIR     = "examples/paper/figures/figure3/"
# ──────────────────────────────────────────────────────────────────────────────

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(BACKUP_DIR, exist_ok=True)

models = {
    "Ankh":   "Ankh/per_residue/",
    "ESM2":   "ESM2/per_residue/",
    "ProstT5": "ProstT5/per_residue",
    "ProtT5": "ProtT5/per_residue",
}

distance_metric = "cosine"
k_values        = [5, 10, 20, 30, 50, 100]
feature_col     = "binding"

# F1 scores as reported by Heinzinger et al. (2023)
ml_performance = {
    "ProtT5":  0.39,
    "Ankh":    0.39,
    "ESM2":    0.35,
    "ProstT5": 0.37,
}
model_order = ["Ankh", "ProtT5", "ProstT5", "ESM2"]

metadata = pd.read_csv(FEATURES_CSV)
print(f"Residues: {len(metadata):,}")

ema = Emma(feature_data=metadata)
for alias, subdir in models.items():
    ema.add_emb_space(
        embeddings_source=EMBEDDINGS_DIR + subdir,
        emb_space_name=alias,
    )

# Load or compute cached rank arrays (already mean-centred in backup_dir)
num_samples = len(ema.metadata)
for model in models:
    ranks_path = os.path.join(BACKUP_DIR, f"{model}_{distance_metric}_ranks.npy")
    if os.path.exists(ranks_path):
        print(f"[{model}] Loading cached ranks from {ranks_path}")
        ranks = np.load(ranks_path)
        if "ranks" not in ema.emb[model]:
            ema.emb[model]["ranks"] = {}
        ema.emb[model]["ranks"][distance_metric] = ranks
    else:
        print(f"[{model}] Computing pairwise distances...")
        ema.calculate_pairwise_distances(emb_space=model, metric=distance_metric)
        np.save(ranks_path, ema.emb[model]["ranks"][distance_metric])
        print(f"  Saved to {ranks_path}")

protein_ids = ema.metadata["residue_id"]
knn_scores_df = pd.DataFrame(columns=["Sample", "Class", "Fraction", "Embedding", "k"])

for k_value in k_values:
    print(f"Computing KNN alignment (cosine, k={k_value})...")
    scores = get_knn_alignment_scores(
        ema,
        feature=feature_col,
        k=k_value,
        metric=distance_metric,
        adjust_for_imbalance=False,
    )
    scores["k"] = k_value
    scores["Sample"] = np.tile(protein_ids.values, len(models))
    knn_scores_df = pd.concat([knn_scores_df, scores], ignore_index=True)

df_grouped = (
    knn_scores_df
    .groupby(["k", "Embedding"], as_index=False)
    .agg({"Fraction": "mean"})
)

plot_model_ranking(
    df_knn=df_grouped,
    ml_performance=ml_performance,
    model_order=model_order,
    knn_y_title="Mean KNN alignment score",
    ml_y_title="F1 score <br>(as reported by Heinzinger et al.)",
    ml_y_range=[0.30, 0.45],
    knn_dtick=0.01,
    ml_text_fmt="{:.2f}",
    title="C. Residue binding (binary)",
    output_path=OUTPUT_DIR + "figure3c_residue_binding.pdf",
)

print(f"Saved figure3c_residue_binding.pdf to {OUTPUT_DIR}")
