"""
Figure 3B — Residue conservation: embedding space ranking
==========================================================
Reproduces Figure 3B

Panel layout (generated by shared_figures.plot_model_ranking):
  Left:  KNN feature alignment score vs k (cosine, ANNOY, k in [5,10,20,30,50,100])
  Right: Bar chart of Q9 conservation accuracy as reported by Heinzinger et al. (2024)

PLMs compared: Ankh, ESM2, ProtT5, ProstT5
Output saved to: examples/paper/figures/figure3/figure3b_conservation.pdf
"""

import os
import sys

import numpy as np
import pandas as pd
import plotly.colors as pc

from emmaemb.core import Emma
from emmaemb.functions import get_knn_alignment_scores

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))
from shared_figures import plot_model_ranking

# ── Path placeholders — fill in before running ─────────────────────────────────
EMBEDDINGS_DIR = "examples/paper/data/conservation/embeddings/"   # subdirs: ModelName/per_residue/
FEATURES_CSV   = "examples/paper/data/conservation/processed/conservation_features.csv"
BACKUP_DIR     = "examples/paper/data/conservation/annoy_indices/"      # cached ANNOY rank arrays
OUTPUT_DIR     = "examples/paper/figures/figure3/"
N_TREES        = 100
# ──────────────────────────────────────────────────────────────────────────────

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(BACKUP_DIR, exist_ok=True)

models = {
    "Ankh":   "Ankh/per_residue",
    "ESM2":   "ESM2/per_residue",
    "ProtT5": "ProtT5/per_residue",
    "ProstT5": "ProstT5/per_residue",
}

distance_metric      = "cosine"
annoy_metric_key     = "angular"   # ANNOY's internal name for cosine
k_values             = [5, 10, 20, 30, 50, 100]
feature_col          = "conservation"

# Q9 conservation accuracy as reported by Heinzinger et al. (2023)
ml_performance = {
    "ProtT5":  33.4,
    "Ankh":    34.4,
    "ESM2":    33.7,
    "ProstT5": 30.9,
}
model_order = ["Ankh", "ESM2", "ProtT5", "ProstT5"]

metadata = pd.read_csv(FEATURES_CSV)
print(f"Residues: {len(metadata):,}")

ema = Emma(feature_data=metadata)

# Load cached ANNOY rank arrays (built with mean-centering)
for model_alias, model_subdir in models.items():
    annoy_path = os.path.join(BACKUP_DIR, f"{model_alias}_mc_{distance_metric}_{N_TREES}_knn.npy")

    if os.path.exists(annoy_path):
        print(f"[{model_alias}] Loading cached ANNOY ranks from {annoy_path}")
        if model_alias not in ema.emb:
            ema.emb[model_alias] = {}
        if "annoy_ranks" not in ema.emb[model_alias]:
            ema.emb[model_alias]["annoy_ranks"] = {}
        if annoy_metric_key not in ema.emb[model_alias]["annoy_ranks"]:
            ema.emb[model_alias]["annoy_ranks"][annoy_metric_key] = {}
        ema.emb[model_alias]["annoy_ranks"][annoy_metric_key][N_TREES] = np.load(annoy_path)
    else:
        print(f"[{model_alias}] Computing ANNOY index (this may take several minutes)...")
        ema.add_emb_space(
            embeddings_source=EMBEDDINGS_DIR + model_subdir,
            emb_space_name=model_alias,
        )
        ema.mean_center(emb_spaces=[model_alias])
        ema.build_annoy_index(
            emb_space=model_alias,
            metric=distance_metric,
            n_trees=N_TREES,
            max_k=max(k_values),
        )
        np.save(annoy_path, ema.emb[model_alias]["annoy_ranks"][annoy_metric_key][N_TREES])
        print(f"  Saved to {annoy_path}")

protein_ids = ema.metadata["residue_id"]
knn_scores_df = pd.DataFrame(columns=["Sample", "Class", "Fraction", "Embedding", "k"])

for k_value in k_values:
    print(f"Computing KNN alignment (ANNOY cosine, k={k_value})...")
    scores = get_knn_alignment_scores(
        ema,
        feature=feature_col,
        k=k_value,
        metric=distance_metric,
        adjust_for_imbalance=False,
        use_annoy=True,
        n_trees=N_TREES,
        annoy_metric=distance_metric,
    )
    scores["k"] = k_value
    scores["Sample"] = np.tile(protein_ids.values, len(models))
    knn_scores_df = pd.concat([knn_scores_df, scores], ignore_index=True)

df_grouped = (
    knn_scores_df
    .groupby(["k", "Embedding"], as_index=False)
    .agg({"Fraction": "mean"})
)

plot_model_ranking(
    df_knn=df_grouped,
    ml_performance=ml_performance,
    model_order=model_order,
    knn_y_title="Mean KNN alignment score *",
    ml_y_title="Q9 accuracy <br>(as reported by Heinzinger et al.)",
    ml_y_range=[28, 37],
    knn_dtick=0.01,
    ml_text_fmt="{:.1f}%",
    title="B. Residue conservation",
    output_path=OUTPUT_DIR + "figure3b_conservation.pdf",
)

print(f"Saved figure3b_conservation.pdf to {OUTPUT_DIR}")
