"""
Figure 3A — Subcellular localization: embedding space ranking
=============================================================
Reproduces Figure 3A

Panel layout (generated by shared_figures.plot_model_ranking):
  Left:  KNN feature alignment score vs k (cosine, mean-centred, k in [5,10,20,30,50,100])
         One line per PLM; elbow at the recommended k.
  Right: Bar chart of Q10 accuracy as reported by Heinzinger et al. (2024)

PLMs compared: ProtT5, Ankh, ESM2, ProstT5
Output saved to: examples/paper/figures/figure3/figure3a_deeploc.pdf
"""

import os
import sys

import numpy as np
import pandas as pd
import plotly.colors as pc

from emmaemb.core import Emma
from emmaemb.functions import get_knn_alignment_scores

# Resolve the shared_figures module relative to this script location
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))
from shared_figures import plot_model_ranking

# ── Path placeholders — fill in before running ─────────────────────────────────
EMBEDDINGS_DIR = "examples/paper/data/deeploc/embeddings/"        # subdirs: Ankh/, ESM2/, ProstT5/, ProtT5/
FEATURES_CSV   = "examples/paper/data/deeploc/processed/deeploc_train_features.csv"
OUTPUT_DIR     = "examples/paper/figures/figure3/"
# ──────────────────────────────────────────────────────────────────────────────

os.makedirs(OUTPUT_DIR, exist_ok=True)

sub_loc_abbreviation_mapping = {
    "Cell.membrane": "Mem",
    "Cytoplasm": "Cyt",
    "Endoplasmic.reticulum": "End",
    "Golgi.apparatus": "Gol",
    "Lysosome/Vacuole": "Lys",
    "Mitochondrion": "Mit",
    "Nucleus": "Nuc",
    "Peroxisome": "Per",
    "Plastid": "Pla",
    "Extracellular": "Ext",
}

models = {
    "Ankh":   "Ankh",
    "ESM2":   "ESM2",
    "ProstT5": "ProstT5",
    "ProtT5": "ProtT5",
}

k_values = [5, 10, 20, 30, 50, 100]
distance_metric = "cosine"

# Q10 accuracy as reported by Heinzinger et al. (2023)
ml_performance = {
    "ProtT5":  64.9,
    "Ankh":    63.7,
    "ESM2":    62.9,
    "ProstT5": 57.3,
}
model_order = ["ProtT5", "Ankh", "ESM2", "ProstT5"]

# Load metadata and abbreviate localization labels
metadata = pd.read_csv(FEATURES_CSV)
metadata["Subcellular Localization"] = metadata["subcellular_location"].map(
    sub_loc_abbreviation_mapping
)

# Load embeddings and apply mean-centering
ema = Emma(feature_data=metadata)
for alias, subdir in models.items():
    ema.add_emb_space(
        embeddings_source=EMBEDDINGS_DIR + subdir,
        emb_space_name=alias,
    )
ema.mean_center(list(models.keys()))

# Compute pairwise distances (cosine, mean-centred)
for model in models:
    ema.calculate_pairwise_distances(emb_space=model, metric=distance_metric)

# Collect KNN alignment scores across k values
protein_ids = ema.metadata["protein_name"]
knn_scores_df = pd.DataFrame(
    columns=["Sample", "Class", "Fraction", "Embedding", "k"]
)

for k_value in k_values:
    print(f"Computing KNN alignment (cosine, k={k_value})...")
    scores = get_knn_alignment_scores(
        ema,
        feature="Subcellular Localization",
        k=k_value,
        metric=distance_metric,
        adjust_for_imbalance=False,
    )
    scores["k"] = k_value
    scores["Sample"] = np.tile(protein_ids.values, len(models))
    knn_scores_df = pd.concat([knn_scores_df, scores], ignore_index=True)

df_grouped = (
    knn_scores_df
    .groupby(["k", "Embedding"], as_index=False)
    .agg({"Fraction": "mean"})
)

# Generate and save Figure 3A
plot_model_ranking(
    df_knn=df_grouped,
    ml_performance=ml_performance,
    model_order=model_order,
    knn_y_title="Mean KNN alignment score",
    ml_y_title="Q10 accuracy <br>(as reported by Heinzinger et al.)",
    ml_y_range=[54, 68],
    knn_dtick=0.05,
    ml_text_fmt="{:.1f}%",
    title="A. Subcellular localization",
    output_path=OUTPUT_DIR + "figure3a_deeploc.pdf",
)

print(f"Saved figure3a_deeploc.pdf to {OUTPUT_DIR}")
